name: MdEditor

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - main

jobs:
  build:
    name: Build MdEditor
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Swift 6.0 via swiftenv
        run: |
          brew install swiftenv
          swiftenv install 6.0
          swiftenv global 6.0
          swift --version
          
      - name: Install Tuist
        run: |
          brew tap tuist/tuist
          brew install --formula tuist@4.43.1
          
      - name: Build
        run: ./.github/build.sh
        
      - name: Test
        run: ./.github/test.sh
