name: MdEditor
on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - main

jobs:
  build:
    name: Build MdEditor
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: brew tap tuist/tuist
      - run: brew install --formula tuist@4.43.1
      - name: Build
        run: exec ./.github/build.sh
      - name: Test
        run: exec ./.github/test.sh
