name: TaskManagerPackage

on:
  pull_request:
    branches:
      -develop

jobs:
  build:
    name: Test DataStructuresPackage
    runs-on: macos-latest
    steps:
      - Uses: actions/checkout@v3
      - name: Build
        run: |
         cd Packages/TaskManagerPackage
         swift build -v
      - name: Run tests
        run: |
         cd Packages/TaskManagerPackage
         swift test -v

